### PR TITLE
Add basic Linux build Action

### PR DESCRIPTION
**Pull request by amoeba**
Hey @tjhancocks, I saw your comment in https://github.com/EvocationGames/KestrelEngine/pull/45#issuecomment-792538307 and thought I'd have a go at a basic Linux build using GitHub Actions. I made my best guess in a few places but let me know if you see anything that looks weird.

If you look at the [last run on my fork](https://github.com/amoeba/KestrelEngine/runs/2055399377?check_suite_focus=true) you'll see the build is failing due to what appears to be a missing `#include <stdexcept>` in graphite so I think this is doing its job. @warnwar any chance you'd take a look at this too?

Hope you might find this useful.

### CODE REVIEW

**Comment by tjhancocks** [comment]
Ah super awesome!

Yeah this is going to be a running theme across each of the repositories, with various short comings in Linux and (eventually) Windows builds due to inconsistent build environments.

I've never actually used GitHub actions before (KDL was using Travis, but that is shutting down its existing free offering), but can it do builds for Windows, Linux and macOS? I'm really wanting to get to a point where each of the repo's PR's are verified on each toolchain.

**Comment by tjhancocks** [comment]
As for the PR, I want to get this added to Graphite first, and the fix put in place there, as well as in KDL, before merging this.

**Comment by amoeba** [comment]
>  can it do builds for Windows, Linux and macOS?

Yep, it totally can! I'm actually about to add a macOS build workflow I cooked up this morning once I make sure it works. It reports another error which is _also_ an error I get on my system when I build. I'm away from a computer for the next few days but I can look at a Windows build some time for sure.

**Comment by amoeba** [comment]
Okay, macOS workflow added. GitHub Actions has a bit of a learning curve (they use tons of magic, but documented, tricks to set things up) but you should more or less be able to copy the `.github` folder in this repo to others to get them running. I can look at doing that later this week if you don't get to it before.

**Comment by warnwar** [comment]
@amoeba This is really cool. I will definitely be looking over these changes in detail for future use as a template.

I can also take a look at the failing Graphite build on your fork and see what I can do, but I can't make any big promises as I'm sort of in over my head with c++ in general.

**Comment by amoeba** [comment]
Right on, @warnwar.

> I can also take a look at the failing Graphite build on your fork and see what I can do, but I can't make any big promises as I'm sort of in over my head with c++ in general.

Same here. As far as I can tell, the graphite build can be fixed by just adding an `#include <stdexcept>` at the top of `data.hpp`.

**Comment by amoeba** [comment]
Hey @tjhancocks, I added similar build workflows over on https://github.com/TheDiamondProject/Graphite/pull/27 and https://github.com/tjhancocks/kdl/pull/43 in case they're a useful starting point.

**Pull request merged**
